(function(){
  const year=document.querySelector('[data-year]'); if(year) year.textContent=new Date().getFullYear();
  const toggle=document.querySelector('.nav-toggle'), nav=document.querySelector('.nav-links');
  if(toggle&&nav){toggle.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
  const reports={
    maps:{kicker:'01 · Google Maps',title:'Adaptive Safety & Comfort Navigation',tagline:'Not just how to get there — but the right way for you.',summary:'Explores how navigation can move beyond directions and help people understand changing road conditions, hazards and comfort before they reach them.',bullets:['RoadSense intelligence for hazards and changing conditions','Route choices that balance fastest, safest, smoothest and most comfortable journeys','Context-aware alerts that help people make better decisions before a risk becomes immediate','A focused product direction that adds safety and awareness without replacing familiar navigation']},
    alexa:{kicker:'02 · Alexa+',title:'From Voice Assistant to Visual AI Companion',tagline:'The next evolution of Alexa+ — making intelligence more visual, interactive and engaging for every member of the household.',summary:'Explores a visual layer for ambient AI: keeping voice effortless while adding visual context when seeing, demonstrating or interacting makes the experience more useful.',bullets:['Expressive visual companion on compatible Echo Show devices','Contextual cards and visual responses when audio alone is limiting','Household experiences across learning, storytelling, entertainment and everyday tasks','Software-first MVP before more ambitious spatial or 3D experiences']},
    sky:{kicker:'03 · SkyServe',title:'Your Airport, Brought to You.',tagline:'Bringing airport food, retail and essentials to the passenger instead of asking the passenger to navigate the terminal for every need.',summary:'A digital airport marketplace designed around passengers who face distance, time pressure, accessibility challenges and limited visibility into what is available around them.',bullets:['Food, retail, duty-free, essentials and airport services in one place','Flight-aware and location-aware discovery','Delivery, pickup and scheduled fulfilment options','Accessibility-first service design for time-constrained and reduced-mobility passengers']},
    kitchen:{kicker:'04 · Kitchen-Genie',title:'Your kitchen, one step ahead.',tagline:'An AI-powered kitchen companion that turns existing ingredients into delicious meals, reduces food waste and makes everyday cooking effortless.',summary:'Connects inventory, freshness, preferences, plans and habits so the kitchen can help decide what to cook, what to use first, what to buy next and what to do with leftovers.',bullets:['Inventory and freshness awareness','Use-first recommendations that turn expiry data into action','Meal planning and grocery intelligence','Personalisation that learns household preferences and habits over time']}
  };
  const modal=document.getElementById('reportModal'), image=document.getElementById('modalImage'), title=document.getElementById('modalTitle'), kicker=document.getElementById('modalKicker'), tagline=document.getElementById('modalTagline'), summary=document.getElementById('modalSummary'), bullets=document.getElementById('modalBullets');
  document.querySelectorAll('[data-report-image]').forEach(img=>{const key=img.dataset.reportImage;if(window.REPORT_IMAGES&&window.REPORT_IMAGES[key]){img.src=window.REPORT_IMAGES[key].thumb;img.loading='lazy';img.decoding='async'}});
  function openReport(key){const d=reports[key];if(!d||!modal)return;kicker.textContent=d.kicker;title.textContent=d.title;tagline.textContent=d.tagline;summary.textContent=d.summary;bullets.innerHTML=d.bullets.map(x=>'<li>'+x+'</li>').join('');if(window.REPORT_IMAGES&&window.REPORT_IMAGES[key]){image.src=window.REPORT_IMAGES[key].full;image.alt=d.title+' visual product report'}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('body-lock');}
  function closeReport(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('body-lock');}
  document.querySelectorAll('.report-card').forEach(card=>{const key=card.dataset.report;card.addEventListener('click',()=>openReport(key));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openReport(key)}})});
  if(modal){modal.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeReport));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeReport()})}
})();
